//CREATE TABLE ADDRESS(ID LONG PRIMARY KEY,CREATION Date,CONTENT varchar(255), AUTEUR varchar(255));

INSERT INTO ADDRESS (ID, CREATION, CONTENT, AUTEUR) VALUES (1, CURRENT_TIMESTAMP(), '57 boulevard demorieux', 'Baptiste');
INSERT INTO ADDRESS (ID, CREATION, CONTENT, AUTEUR) VALUES (2, CURRENT_TIMESTAMP(), '51 allee du gamay, 34080 montpellier','Baptiste');
